### ISSUE TITLE
app.passport.payloadIsValid() returns true when jwt expired

### ISSUE THREAD

**Issue by sarkistlt** [feathersjs/authentication-client#100]
this is what my client looks like:

```js
// REST client
client
  .configure(rest(config.get('api')).superagent(superagent))
  .configure(auth({
      storage: new Cookies(),
      cookie: `worker-jwt_${NODE_ENV}`,
      storageKey: `worker-jwt_${NODE_ENV}`,
  }))
  .hooks({ before: [initAuth(client)] });
```

and `initAuth` is the hook to verify JWT or re authenticate if needed:

```js
function initAuth(app) {
  return (ctx) => {
    if (ctx.path !== 'authentication') {
      return new Promise((resolve) => {
        app.passport.getJWT()
          .then((token) => {
            if (app.passport.payloadIsValid(token)) {
              resolve(ctx);
            } else {
              app.authenticate(config.get('apiAuth'))
                .then(() => resolve(ctx))
                .catch((err) => {
                  logger.error(err);
                  resolve(ctx);
                });
            }
          })
          .catch(() => {
            app.authenticate(config.get('apiAuth'))
              .then(() => resolve(ctx))
              .catch((err) => {
                logger.error(err);
                resolve(ctx);
              });
          });
      });
    }
    return ctx;
  };
}
```

so in this example I'm using `app.passport.payloadIsValid` and for some reason sometime I'm still getting error `jwt expired`, which shouldn't be possible with this hook. If I will replace `app.passport.payloadIsValid` with `app.passport.verifyJWT` like this:

```js
function initAuth(app) {
  return (ctx) => {
    if (ctx.path !== 'authentication') {
      return new Promise((resolve) => {
        app.passport.getJWT()
          .then((token) => {
            app.passport.verifyJWT(token)
              .then(() => resolve(ctx))
              .catch(() => {
                app.authenticate(config.get('apiAuth'))
                  .then(() => resolve(ctx))
                  .catch((err) => {
                    logger.error(err);
                    resolve(ctx);
                  });
              });
          })
          .catch(() => {
            app.authenticate(config.get('apiAuth'))
              .then(() => resolve(ctx))
              .catch((err) => {
                logger.error(err);
                resolve(ctx);
              });
          });
      });
    }
    return ctx;
  };
}
```

everything works  fine. So what is the difference between `app.passport.payloadIsValid` and `app.passport.verifyJWT`, besides the first one sync. and returns boolean, aren't they both verify and check if jwt is valid?

**Module versions**
```json
    "@feathersjs/authentication-client": "^1.0.2",
    "@feathersjs/feathers": "^3.0.2",
    "@feathersjs/rest-client": "^1.3.3"
```

**Comment by sarkistlt** [comment]
I just checked the source code and `payloadIsValid` expected decoded token, but in the [docs](https://docs.feathersjs.com/api/authentication/client.html#apppassportpayloadisvalidtoken), it says just a token, so could it be the problem? also `payloadIsValid` is just one line function `return payload && (!payload.exp || payload.exp * 1000 > new Date().getTime());`, so if I will pass token instead of decoded one it should always return false, then how can I get jwt-expired?

**Comment by daffl** [comment]
Client side JWT validation and parsing should no longer be necessary in Feathers v4 authentication. Please see the [migration guide](https://crow.docs.feathersjs.com/migrating.html) for more information. Closing this issue in order to archive this repository. Related issues can be opened at the new code location in the [Feathers main repository](https://github.com/feathersjs/feathers).
