### ISSUE TITLE
Calling app.authenticate() with socket transport does not run hooks.

### ISSUE THREAD

**Issue by DaddyWarbucks** [feathersjs/authentication-client#102]
### Expected behavior
Calling `app.authenticate()` should call the `app.service('authentication')` hooks when using socket.io or primus transports.

### Actual behavior
Hooks are not called because the service is not explicitly called.

I can see on this line: 
https://github.com/feathersjs/authentication-client/blob/4d00bd8b8b2244caa735d6a129b7a16f73d0902b/lib/passport.js#L167
That the service is not explicitly called. I think I generally understand why this is the case, because it actually modifies the transport with the request by setting `socket.authenticated = true` which is fundamentally different than calling the service explicitly which should be transport independent.

It would be great if this method could call the hooks. I understand we would need to "spoof" some context and what not, but having the method work transport independently like everything else would be nice.

Or, we should at least mention this behavior in the documentation.

I toyed around a bit, but it was quite a bit of fuss to handle the different responses that a hook can have, context, promise, err, undefined, etc. Note this is not a complete, or even working, example. Just a snippet of some code I threw at it.
```
  app._authenticate = async (credentials) => {
    const beforeHooks = app.services.authentication.__hooks.before.create
    const context = beforeHooks.reduce(async (context, hook) => {
      console.log({ context })
      return await hook(context).catch(err => { throw err });
    }, { data: credentials, type: 'before', app, params: {} } )
    console.log(context)
    return
    const token = await app.authenticate(context.data)
  ...
```

For anyone interested, I have "solved" this problem by creating and calling my own `_authenticate` method that just manually does some things I would normally handle in hooks.
```
import feathers from '@feathersjs/client'
import authLib from '../lib/auth'
import { validate } from './hooks'
import { appContainer } from '../contexts/app'

const validateCreds = validate({
  email: 'Email is required.',
  password: 'Password is required.'
})

// Set the sessions in storage. These "sessions" are an
// array of objects. Each obj contains a valid accessToken and
// account name, which are stored in localStorage and used by the
// UI to assemble a "Switch Accounts" mechanism.
// TODO: This doesn't really need to be stored in localStorage anymore.
// As the app's state container has grown and our auth strategy has changed
// this makes just as much sense to put in the app's state container rather
// than in localStorage
const setStorage = async (context) => {
  await authLib.setStorage(context.result.sessions)
  return context
}

export default (app) => {
  // Setup the authentication service, which adds
  // app.authenticate method
  app.configure(feathers.authentication({
    storage: localStorage,
    storageKey: 'mapplug-token'
  }))

  // Unfortunately the socket.io transport does not
  // call the underlying app.service('authentication') service
  // and fire its hooks. So, we have to wrap this function in
  // another method which calls the sessions service and
  // sets state, which we could do in a hook if the service were
  // actually called by the socket transport
  app._authenticate = async (credentials) => {
    // User our own validation hook by passing it an object
    // that looks like `context`
    const { data: creds } = validateCreds({ data: credentials })
    const token = await app.authenticate(creds)
    // the sessions service after hook will store the session
    // data in localStorage. Note that the sessions service is
    // prtected serverside by auth hook.
    await app.service('api/sessions').find()
    // Set the authenticated state to true, which will inform
    // the prepApp function that the feathers instance has already
    // been authenticated (else it will run _authenticate there).
    // An authenticated feathers instance will automatically attach the token
    // from storage and do some other stuff on each request.
    // TODO: Should this be handled in an app.hooks() before all hook?
    // Before each call, check that the feathers instance/socket is already
    // authed and if not auth it? This may be better. Since I have namespaced
    // the services, it would be easy to check
    // `if context.service.name.startsWith("api")`...check auth status and
    // either auth it or let it pass. But, our prepApp function is running
    // before we get to any authenticated calls, so this is fine too
    appContainer.set('authenticated', true)
    return token
  }

  // NOTE: Hooks placed on the `authentication` service do not actually run
  // see the _authentication method above
  //app.service('authentication').hooks({ })
  app.service('api/sessions').hooks({
    after: {
      find: [setStorage]
    }
  })
  app.service('auth/accept-invite').hooks({
    before: {
      update: [deleteUserId]
    }
  })
}

// Passing a user up to the accept-invite service does
// not run through the normal `fromImmutable` hook which
// removes the _id is creating. Remove it manually so that
// the server does not barf about trying to create a user with
// and _id already set.
const deleteUserId = (context) => {
  if (context.data.user && context.data.user.toJS) {
    context.data.user = context.data.user.toJS()
    delete context.data.user._id
    return context
  } else {
    return context
  }
}
```

**Comment by daffl** [comment]
`app.service('authentication').create()` is still called on the server during socket authentication [here](https://github.com/feathersjs/authentication/blob/master/lib/socket/handler.js#L93).

This problem will also be fixed in the next version by using [params.connection](https://docs.feathersjs.com/api/socketio.html#paramsconnection).

**Comment by DaddyWarbucks** [comment]
This issue is really just meant for the client side method.
For example, I want to use a `before` hook to add better validation than the `Missing Credentials` error message that the `app.authenticate()` returns locally.

When you say this problem will be fixed in the next version with `params.connection`, does that mean that the client will run hooks?

**Comment by daffl** [comment]
Yep. Basically `app.authenticate()` will just be a wrapper for the client side `app.service('authentication').create()` and work with all client side hooks. No more separate [socket `authenticate` event](https://docs.feathersjs.com/api/client/socketio.html#authentication) because the `accessToken` will just be attached to the connection automatically.

Looking forward to changing that because things like getting/setting the token in localStorage on the client can then just be a hook, too.

**Comment by DaddyWarbucks** [comment]
Thanks! You can close this!

**Comment by daffl** [comment]
Closing this one, related https://github.com/feathersjs/authentication-client/issues/67
