### ISSUE TITLE
Logout not working 

### ISSUE THREAD

**Issue by navneet-baidwan** [feathersjs/authentication-client#103]
app.logout not working in my react native app. 

    this.app.logout().then(() => {
      console.log('logged out...')
    })
    .catch(err =>{console.log('error in logout')})

I am not getting promise callback or catch err

**Comment by daffl** [comment]
For [React Native usage](https://docs.feathersjs.com/api/client.html#react-native) it is very important to properly configure the connection by forcing the websocket transport:

```js
const socket = io('http://api.my-feathers-server.com', {
  transports: ['websocket']
});
```

This usually solves 90% of all React Native problems.
