### ISSUE TITLE
Interpolated strings are causing issues with IE 11

### ISSUE THREAD

**Issue by dschnare** [feathersjs/authentication-client#106]
Since the code base has interpolated strings throughout, when bundling with Webpack/Nextjs we can't load the client bundle in IE 11 or browsers that do not support interpolated strings. This occurs because Webpack does not compile modules installed using `node_modules` it just bundles them.

Related https://github.com/feathersjs/errors/pull/117
Related https://github.com/feathersjs/rest-client/issues/35

**Comment by daffl** [comment]
See https://github.com/feathersjs/rest-client/issues/35
