### ISSUE TITLE
Consider the case that hook.params maybe undefined or null

### ISSUE THREAD

**Issue by testless** [feathersjs/authentication-client#114]
Refering to https://github.com/feathersjs/feathers/issues/1001

https://github.com/feathersjs/authentication-client/blob/5bcf78e3c96ea9f7d56d1ba5df5d473ce845a912/lib/hooks/populate-access-token.js#L9

**Comment by bertho-zero** [comment]
This should not happen with the latest installed version (https://github.com/feathersjs/feathers/issues/1001#issuecomment-423228192)
