### ISSUE TITLE
This module can be archived

### ISSUE THREAD

**Issue by bertho-zero** [feathersjs/authentication-client#115]
# THIS MODULE HAS BEEN MOVED TO https://github.com/feathersjs/feathers

Please open any issues there. This repository will be archived once all open issues have been addressed.

**Comment by daffl** [comment]
GitHub recommends to close all open issues before archiving a repository. This one and `feathers/authentication` still have some outstanding issues that will be closed in the next version (and the remaining ones can be moved then).
