### ISSUE TITLE
Token Expires when the client is still connected

### ISSUE THREAD

**Issue by achilsowa** [feathersjs/authentication-client#138]
Hi guys

I'm using the default authentication configuration (as describe in the [chat example](https://docs.feathersjs.com/guides/chat/authentication.html))
I tried to modify the expiresIn field in default.json to 15s. And after 15s, the token expires even if I'm still using the connection.
May be I'm wrong, but I expected the expiresIn to take effect after inaction from the client but it does not seems to be the case.
And a question from that "pseudo issue" (I'm not sure it is an issue actually, may be it is the default behavior), how can be notifiy after token expires (an event may be) ? I only see an error in the console, but it would be nice if we can listen to that event so we could clear user session and stuff like that.

Thanks

**Comment by daffl** [comment]
Once issued, the information in a JWT can not be changed. This includes its expiration time, so it can't really account for inactivity. The standard settings are usually good enough for most use cases.
