### ISSUE TITLE
'authenticate' should return anonymous JWT when applicable

### ISSUE THREAD

**Issue by petermikitsh** [feathersjs/authentication-client#21]
### Steps to reproduce

```js
/** Assume window.localStorage has no JWT, no JWT in cookies, e.g.,
  * window.localStorage #=> Storage {length: 0} 
  * document.cookie #=> ""
  */

import auth from 'feathers-authentication-client';
import feathers from 'feathers/client';
import hooks from 'feathers-hooks';
import io from 'socket.io-client';
import socketio from 'feathers-socketio/client';

const app = feathers()
  .configure(hooks())
  .configure(socketio(socket))
  .configure(auth({
    path: 'api/authentication',
    storage: window.localStorage,
    storageKey: 'authtoken'
  }));

app
  .authenticate({strategy: 'jwt'})
  .catch((e) => {
    console.log('Could not authenticate', e);
  });
```

### Expected behavior

I expected to get an anonymous JWT from the `api/authentication` service.

### Actual behavior

<img width="306" alt="screen shot 2017-01-14 at 4 10 59 pm" src="https://cloud.githubusercontent.com/assets/1571918/21959172/073b228c-da74-11e6-8774-5775a1cc6e18.png">

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working): 
**feathers-authentication-client**: 0.1.6
**NodeJS version**: 6.x
**Operating System**: OS X
**Browser Version**: Chrome, Latest
**React Native Version**: N/A
**Module Loader**: Webpack

### Notes

It makes sense for `authenticate` to return an anonymous JWT that way it plays nicely with the `auth.hooks.authenticate('jwt')` hook. More context in this comment here: https://github.com/feathersjs/feathers-authentication/issues/396#issuecomment-272662062.

**Comment by kirkchris** [comment]
@petermikitsh, I am hitting this issue as well. Did you have any luck with a workaround to generate anonymous jwts for requests when you wish to allow that to proceed? I believe the blocking factor is the `auth.hooks.authenticate()` in the `before` of create.

```
app.service('authentication').before({
    create: [
      // auth.hooks.authenticate(['jwt', 'local']),
    ],
    remove: [
      auth.hooks.authenticate('jwt'),
    ],
  });
```

**Comment by daffl** [comment]
Anonymous strategy support has been aded for Feathers v4. Please see the [migration guide](https://crow.docs.feathersjs.com/migrating.html) for more information. Closing this issue in order to archive this repository. Related issues can be opened at the new code location in the [Feathers main repository](https://github.com/feathersjs/feathers).
