### ISSUE TITLE
Authentication timed out With SocketIO Transport

### ISSUE THREAD

**Issue by abalad** [feathersjs/authentication-client#89]
### Steps to reproduce

- [ ] Creating a Basic ServerSide Project Using Rethinkdb as a Data Provider
- [ ] Copy and paste the code into an index.js file.
- [ ] Execute the code using the node index.js command

### Expected behavior
Perform authentication / reauthentication via socketServer

### Actual behavior
When you authenticate or reauthenticate using Transport SocketIO, the Client returns a Timeout message
` Authentication timed out
    at setTimeout (passport.js:180)
    at ZoneDelegate.invokeTask (zone.js:421)
    at Object.onInvokeTask (core.js:4724)
    at ZoneDelegate.invokeTask (zone.js:420)
    at Zone.runTask (zone.js:188)
    at ZoneTask.invokeTask (zone.js:496)
    at ZoneTask.invoke (zone.js:485)
    at timer (zone.js:2025)`

### System configuration
//

//CODE CLIENT
`const feathers = require('@feathersjs/feathers');
const auth = require('@feathersjs/authentication-client');
const io = require('socket.io-client');
const socketio = require('@feathersjs/socketio-client');
const localStorage = require('localstorage-memory');

const socket = io('http://localhost:3030', {});

const app = feathers();

app.configure(socketio(socket))
   .configure(auth({ storage: localStorage }));

app.authenticate({
  strategy: 'local',
  email: 'user@email',
  password: '123456'
})
  .then(response => {
  console.log('Authenticated!', response);
  return app.passport.verifyJWT(response.accessToken);
})
.then(payload => {
    console.log('JWT Payload', payload);
    return app.service('users').get(payload.userId);
})
.then(user => {
    app.set('user', user);
    console.log('User', feathersClient.get('user'));
})
.catch(function(error){
  console.error('Error authenticating!', error);
});`

**Module versions** (especially the part that's not working):
CLIENT
    "@feathersjs/authentication-client": "^1.0.2",
    "@feathersjs/client": "^3.3.0",
    "@feathersjs/feathers": "^3.1.0",
    "@feathersjs/rest-client": "^1.3.3",
    "@feathersjs/socketio-client": "^1.0.2"
SERVER 
   "@feathersjs/authentication": "^2.1.1",
    "@feathersjs/authentication-jwt": "^2.0.0",
    "@feathersjs/authentication-local": "^1.1.0",
    "@feathersjs/configuration": "^1.0.2",
    "@feathersjs/errors": "^3.2.2",
    "@feathersjs/express": "^1.1.2",
    "@feathersjs/feathers": "^3.1.0",
    "@feathersjs/socketio": "^3.1.0",

**NodeJS version**:
V7.10.0

**Operating System**:
Win10

**Module Loader**:
Webpack from  AngularCli

**Comment by daffl** [comment]
I don't think this is a general issue so it probably has something to do with (I'm assuming) Zones. Try using this setup outside of Angular to see if it is still happening.

**Comment by abalad** [comment]
It also occurs outside the Angular. This code I put in the issue was run with node index.js.

**Comment by abalad** [comment]
I updated the issue by describing these steps better. But in summary it seems that @ feathersjs / socketio-client / socket.io-client is not being able to connect to the server using SocketAdapter.

**Comment by daffl** [comment]
Did you clone the [feathers-chat](https://github.com/feathersjs/feathers-chat) and were able to verify the same issue? I just verified that everything works on Windows on the weekend so it has to be something more specific to your setup (firewalls, build tools, incompatible versions).

**Comment by abalad** [comment]
I'm going to test with feather-char and let me know

**Comment by abalad** [comment]
@daffl I found what is causing the problem but I have no idea how to correct it for you;

In the **Server APP.js** File. When feather-cli is configuring rethinkdb it makes the following configuration:

.... _MORE CODE HERE_
> // Set up Plugins and providers
> **app.configure(express.rest());** //1
> **app.configure(socketio());**       //2

> **app.configure(rethinkdb);**       //3 << HERE CAUSES THE ERROR
... _MORE CODE HERE_

But when I put the configuration of rethinkdb before socketio everything returns to normal
.... _MORE CODE HERE_
> // Set up Plugins and providers
> **app.configure(rethinkdb);**           //1<< HERE IT WORKS NORMAL

> **app.configure(express.rest());**   //2
> **app.configure(socketio());**         //3  
> 
... _MORE CODE HERE_

**Comment by daffl** [comment]
This can now be fixed by upgrading to `feathers-rethinkdb@0.5.1` and changing `src/rethinkdb.js` as in the PR at https://github.com/feathersjs/generator-feathers/pull/337/files

**Comment by abalad** [comment]
thx @daffl
