### ISSUE TITLE
Passport socketAuthenticate doesn't emit a post-authentication event

### ISSUE THREAD

**Issue by bmomberger-bitovi** [feathersjs/authentication-client#90]
For initial authentication, I can do something like

```
feathersClient.passport.app.on('authenticated', () => { ... })
```

And when authentication is complete, this callback will be fired.

However, if the connection is interrupted, after reconnection and re-authentication there is no event emitted:

> initial authentication starts from `Passport#authenticate`, which calls `Passport#authenticateSocket` and then emits an event after completion:  https://github.com/feathersjs/authentication-client/blob/master/lib/passport.js#L167

> When reconnecting, `Passport#authenticateSocket` is called directly, not through `Passport#authenticate`.  It does not emit any events of its own and its returned promise is not exposed by the caller.

While I can listen to the `reconnected` event on the underlying socket.io connection, this fires *before* authentication has happened.

What I'd like to have is an event that can be listened on that covers the reconnect->authenticate socket process completion, so e.g. `reauthenticated` for just reconnections or `socketAuthenticated` that covers both initial connection and reconnection.

**Comment by daffl** [comment]
Maybe https://github.com/feathersjs/authentication-client/blob/master/lib/passport.js#L240 is the best place to emit the event.

**Comment by jamesholcomb** [comment]
I implemented the `socket-authenticated` event in my fork: https://github.com/jamesholcomb/authentication-client/blob/master/lib/passport.js

My react native app uses a Mobx observable to track that state to prevent service calls from being emitted before the socket has been authenticated on `reconnect`.

It works fine when the app is foreground, but a background AppState will not respond to socket events (disconnect from ping timeout or the OS decides to close the network connection).  For instance, on app resume from a push notification, a service call occurring before socket.io has completed reconnection and authentication will timeout.  It seems you must emit on socket and handle the timeout to inspect connection status.

I would like to see some sort of backoff/retry and message queueing strategy in transport-commons to enable graceful reconnects.

**Comment by daffl** [comment]
This has been fixed in Feathers v4 authentication. Please see the [migration guide](https://crow.docs.feathersjs.com/migrating.html) for more information. Closing this issue in order to archive this repository. Related issues can be opened at the new code location in the [Feathers main repository](https://github.com/feathersjs/feathers).
