### ISSUE TITLE
Manually set JWT without having to call `app.authenticate()` on each page reload.

### ISSUE THREAD

**Issue by DaddyWarbucks** [feathersjs/authentication-client#91]
I normally work in React and understand how/why one would call the authentication method on app startup, and then not have to call it again when using client side routing to navigate to a new "page".
But, I am setting up an Express app that renders pages on the server. The pages include JS files that access my Feathers api directly (which is a totally separate server). With that said, each navigation to a new page is a full page reload, thus killing the authenticated instance of the feathers client/auth in the browser.
I know that I can retrieve the `token` and then `api.passport.verifyJWT(token)`.
Is there any way to manually set the JWT token so that I do not have to call `app.authenticate()`?

**Comment by daffl** [comment]
If you are using a REST connection you can manually set `params.headers['Authorization']` to the JWT in an application wide `before` hook:

```js
app.hooks({
  before(context) {
    context.params.headers = Object.assign({
      Authorization: myJWT
    }, context.params.headers);
  }
});
```

**Comment by DaddyWarbucks** [comment]
That was the trick! I am using the websocket transport. Thanks for the speedy reply!

I am really loving feathers!

**Comment by russiann** [comment]
But what if I'm using socket client?
