### ISSUE TITLE
Why is "strategy" required for login?

### ISSUE THREAD

**Issue by hongkongkiwi** [feathersjs/authentication-client#94]
I'm wondering why is "strategy" required?

In my own app I have two strategies setup. I renamed them from 'local' to 'email' and 'username' respectively. Each has a different authentication field.

When authenticating with feathers using a REST API I can simply send the JSON, with either username or email field without specifically defining the strategy. So I'm wondering why this plugin forces me to explicitly specify the strategy?

**Comment by daffl** [comment]
It is required for Websockets authentication and when the parameters are ambiguous and will be mandatory everywhere in the next version of Feathers authentication.

**Comment by hongkongkiwi** [comment]
Got it. This would be be good to document. Is there a way for us to capture the error that is sent to the client and send something else? I'm keen for the "strategy" to be a bit obscured. For example I would like to use "type" as the field that is sent to the server instead of strategy.

**Comment by daffl** [comment]
You can customize the `authentication` workflow the same as any other service using [hooks](https://docs.feathersjs.com/api/hooks.html):

```js
app.service('authentication').hooks({
  before: {
    create(context) {
      context.data.strategy = context.data.type;
    }
  },
  error: {
    create(context) {
      // customize context.error here
    }
  }
});
```
