### ISSUE TITLE
How to input extra fields along with email/password to server by local strategy?

### ISSUE THREAD

**Issue by flight9** [feathersjs/authentication-client#96]
I'm using authentication-client and local strategy and socket.io like example code:
```
app.authenticate({
  strategy: 'local',
  email: 'my@email.com',
  password: 'my-password'
}).then(() => {
  // Logged in
}).catch(e => {
  // Show login page (potentially with `e.message`)
  console.error('Authentication error', e);
});
```

### Expected
I would like to input some extra fields along with email/password (eg. captcha or openid to bind with the user) into authenticate() to send to server to authenticate or save to db, but it seems no mechanism for thar purpose.
How can I do this?

**Comment by daffl** [comment]
You can send any fields you want and use them on the `/authentication` in a hook:

```js
app.service('/authentication').hooks({
  before: {
    create(context) {
      // context.data
    }
  }
});
```

The fields that are being used depend on the strategy. The local strategy only takes a username and password.

**Comment by flight9** [comment]
Thanks @daffl . I can get those fields from context.data in before/after create hooks.

Later, I got stuck on another question on server site: https://github.com/feathersjs/authentication/issues/659
Hope u can give me more suggestions, thanks.
