### ISSUE TITLE
How can I use authentication-client with authentication-oauth2?

### ISSUE THREAD

**Issue by flight9** [feathersjs/authentication-client#98]
### Question1: 
After configuration, should I use authentication-client like this?
```
app.authenticate({
  strategy: '<strategy-name>' // facebook/twitter/wechat
  //here seems no extra params
}).then(() => {
  // Logged in
}).catch(e => {
  // Show login page (potentially with `e.message`)
  console.error('Authentication error', e);
});
```
### Question2: 
In passport.js the following routes are done in client browser and there are redirects inside:
```
app.get('/auth/provider', passport.authenticate('provider')); 
app.get('/auth/provider/callback', passport.authenticate('provider', { successRedirect: '/',
                                      failureRedirect: '/login' }));
```
I'm useing Vue(authentication-client) as frontend, and feathers(feathers-authentication) as backend with 'wechat' oauth2 strategy.
Things seems to get complicated, how can I make those redirects happen only in Vue client and send 'code' or othe variable to backend to go on next steps, using authentication-client api?
I wonder if authentication-client is suitable for OAuth2 in the scenario I met.
Or there is an example of authentication-client to explain that?

**Comment by daffl** [comment]
The client usage is [documented here](https://docs.feathersjs.com/api/authentication/oauth2.html#client-usage). The user has to follow the link to `/auth/<strategy name>` and then redirect back to you client side app which then has to call [app.authenticate() (with no parameter)](https://docs.feathersjs.com/api/authentication/client.html#appauthenticate).

**Comment by flight9** [comment]
@daffl thanks for links
If I unstood correctly from the docs, the diagram will be like following:
![default](https://user-images.githubusercontent.com/1070457/38462582-2d3c5866-3b1c-11e8-88a8-dca00db0045c.png)

Then my next question is that after 'redirect to provider', how will the client know the correct timing to call app.authenticate()?

**Comment by flight9** [comment]
@daffl I do not understand:
> ... and then **redirect back to you client side app** which then has to call app.authenticate() (with no parameter).

In fact, it do not redirect back to my client app, it carries the **code**, so it has to redirect to server side(/auth/provider/callback, see the diagram above) to exchage for accessToken and further verification.
So I wonder when for client app to call app.authenticate().

**Comment by daffl** [comment]
The usual way is to enable cookies with

```js
cookie = {
        enabled: true,
        name: 'feathers-jwt',
        httpOnly: false,
        secure: false
      }
```

in the authentication configuration. Then the generated token is set as `feathers-jwt` in the cookie which will automatically be used by `app.authenticate()`.
